language: node_js
services:
  - docker
node_js:
  - 12
jobs:
  include:
    - stage: master
      name: "master"
      if: branch = master
      script: 
        - npm install -g hexo
        - hexo clean
        - hexo generate
        - git remote -v
        - git tag
        - export TZ='Asia/Shanghai'
        - VERSION=$(node ./source/static/scripts/auto-versioning.js)
        - echo $VERSION
        - git tag -a -f blog/master-v$VERSION -m "Travis CI Auto Tag `date +"%Y-%m-%d %H:%M:%S"`"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git blog/master-v$VERSION
        - git checkout --orphan blog/master
        - git config user.name "Travis CI"
        - git branch -v -a
        - git rm --cached -r -f .
        - rm -rf `ls | grep -v public`
        - cp -r ./public/* .
        - rm -rf ./public
        - git add -f .
        - git commit -m "Travis CI Auto Release `date +"%Y-%m-%d %H:%M:%S"`"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git
        - docker build -t ${DOCKER_RPO_LOCAL_MASTER}:$VERSION .
        - docker build -t ${DOCKER_RPO_LOCAL_MASTER}:latest .
        - echo "hub docker"
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWD}
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:$VERSION ${DOCKER_RPO_HUB_MASTER}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:latest ${DOCKER_RPO_HUB_MASTER}:latest
        - docker push ${DOCKER_RPO_HUB_MASTER}:$VERSION
        - docker push ${DOCKER_RPO_HUB_MASTER}:latest
        - echo "aliyun docker"
        - docker login -u ${DOCKER_ALIYUN_USERNAME} -p ${DOCKER_ALIYUN_PASSWD} ${DOCKER_ALIYUN_URL}
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:$VERSION ${DOCKER_RPO_ALIYUN_MASTER}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:latest ${DOCKER_RPO_ALIYUN_MASTER}:latest
        - docker push ${DOCKER_RPO_ALIYUN_MASTER}:$VERSION
        - docker push ${DOCKER_RPO_ALIYUN_MASTER}:latest
        - echo "tencent docker"
        - docker login -u ${DOCKER_TENCENT_USERNAME} -p ${DOCKER_TENCENT_PASSWD} ${DOCKER_TENCENT_URL}
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:$VERSION ${DOCKER_RPO_TENCENT_MASTER}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:latest ${DOCKER_RPO_TENCENT_MASTER}:latest
        - docker push ${DOCKER_RPO_TENCENT_MASTER}:$VERSION
        - docker push ${DOCKER_RPO_TENCENT_MASTER}:latest
    - stage: dev
      name: "dev"
      if: branch = dev
      script: 
        - npm install -g hexo
        - npm info hexo-images-watermark
        - mv -f _config.dev.yml _config.yml
        - hexo clean
        - hexo generate
        - git remote -v
        - git tag
        - export TZ='Asia/Shanghai'
        - VERSION=$(node ./source/static/scripts/auto-versioning.js)
        - echo $VERSION
        - git tag -a -f blog/dev-v$VERSION -m "Travis CI Auto Tag `date +"%Y-%m-%d %H:%M:%S"`"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git blog/dev-v$VERSION
        - git checkout --orphan blog/dev
        - git config user.name "Travis CI"
        - git branch -v -a
        - git rm --cached -r -f .
        - rm -rf `ls | grep -v public`
        - cp -r ./public/* .
        - rm -rf ./public
        - git add -f .
        - git commit -m "Travis CI Auto Release `date +"%Y-%m-%d %H:%M:%S"`"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git
        - docker build -t ${DOCKER_RPO_LOCAL_DEV}:$VERSION .
        - docker build -t ${DOCKER_RPO_LOCAL_DEV}:latest .
        - echo "hub docker"
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWD}
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:$VERSION ${DOCKER_RPO_HUB_DEV}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:latest ${DOCKER_RPO_HUB_DEV}:latest
        - docker push ${DOCKER_RPO_HUB_DEV}:$VERSION
        - docker push ${DOCKER_RPO_HUB_DEV}:latest
        - echo "aliyun docker"
        - docker login -u ${DOCKER_ALIYUN_USERNAME} -p ${DOCKER_ALIYUN_PASSWD} ${DOCKER_ALIYUN_URL}
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:$VERSION ${DOCKER_RPO_ALIYUN_DEV}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:latest ${DOCKER_RPO_ALIYUN_DEV}:latest
        - docker push ${DOCKER_RPO_ALIYUN_DEV}:$VERSION
        - docker push ${DOCKER_RPO_ALIYUN_DEV}:latest
        - echo "tencent docker"
        - docker login -u ${DOCKER_TENCENT_USERNAME} -p ${DOCKER_TENCENT_PASSWD} ${DOCKER_TENCENT_URL}
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:$VERSION ${DOCKER_RPO_TENCENT_DEV}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:latest ${DOCKER_RPO_TENCENT_DEV}:latest
        - docker push ${DOCKER_RPO_TENCENT_DEV}:$VERSION
        - docker push ${DOCKER_RPO_TENCENT_DEV}:latest
    - stage: all
      name: "all"
      script: 
        - docker images
        - ls -a

notifications:
  email:
    recipients:
      - ling_dark_portal@163.com
    on_success: never # default: change
    on_failure: always # default: always