language: node_js
services:
  - docker
node_js:
  - 12
cache:
  apt: true
  directories:
    - node_modules
jobs:
  include:
    - stage: master
      name: "master"
      if: branch = master
      before_script:
        - export TZ='Asia/Shanghai'
        - npm install -g hexo
        - hexo clean
        - hexo generate
      script: 
        - git remote -v
        - git tag
        - VERSION=$(node ./source/static/scripts/auto-versioning.js)
        - echo $VERSION
        - DESCRIPTION=$(node ./source/static/scripts/auto-description.js)
        - echo $DESCRIPTION
        - git config user.name "Travis CI"
        - git tag -a -f blog/master-v$VERSION -m "Travis CI Auto Tag `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git tag -a -f v$VERSION -m "Travis CI Auto Tag `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git blog/master-v$VERSION
        - git push -f https://${GITHUB_USERNAME}:${GITHUB_PASSWD}@github.com/SpiritLing/blog.git v$VERSION
        - git checkout --orphan gh-pages
        - git branch -v -a
        - git rm --cached -r -f .
        - rm -rf `ls | grep -v public`
        - cp -r ./public/* .
        - rm -rf ./public
        - git add -f .
        - git commit -m "Travis CI Auto Release `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git push -f https://${GITHUB_USERNAME}:${GITHUB_PASSWD}@github.com/SpiritLing/blog.git
        - git checkout --orphan blog/master
        - git add -f .
        - git commit -m "Travis CI Auto Release `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git
        - docker build -t ${DOCKER_RPO_LOCAL_MASTER}:$VERSION .
        - docker build -t ${DOCKER_RPO_LOCAL_MASTER}:latest .
        - echo "hub docker"
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWD}
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:$VERSION ${DOCKER_RPO_HUB_MASTER}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_MASTER}:latest ${DOCKER_RPO_HUB_MASTER}:latest
        - docker push ${DOCKER_RPO_HUB_MASTER}:$VERSION
        - docker push ${DOCKER_RPO_HUB_MASTER}:latest
    - stage: dev
      name: "dev"
      if: branch = dev
      before_script:
        - export TZ='Asia/Shanghai' # 改变时区
        - npm install -g hexo
        - mv -f _config.dev.yml _config.yml
        - hexo clean
        - hexo generate
        - git remote -v
        - git tag
        - VERSION=$(node ./source/static/scripts/auto-versioning.js)
        - echo $VERSION
        - DESCRIPTION=$(node ./source/static/scripts/auto-description.js)
        - echo $DESCRIPTION
        - git config user.name "Travis CI"
        - git tag -a -f blog/dev-v$VERSION -m "Travis CI Auto Tag `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git blog/dev-v$VERSION
        - git checkout --orphan blog/dev
        - git branch -v -a
        - git rm --cached -r -f .
        - rm -rf `ls | grep -v public`
        - cp -r ./public/* .
        - rm -rf ./public
        - git add -f .
        - git commit -m "Travis CI Auto Release `date +"%Y-%m-%d %H:%M:%S"` DES：$DESCRIPTION"
        - git push -f https://${CODING_USERNAME}:${CODING_PASSWD}@e.coding.net/spiritling/website.git
      script:
        - docker build -t ${DOCKER_RPO_LOCAL_DEV}:$VERSION .
        - docker build -t ${DOCKER_RPO_LOCAL_DEV}:latest .
        - echo "hub docker"
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWD}
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:$VERSION ${DOCKER_RPO_HUB_DEV}:$VERSION
        - docker tag ${DOCKER_RPO_LOCAL_DEV}:latest ${DOCKER_RPO_HUB_DEV}:latest
        - docker push ${DOCKER_RPO_HUB_DEV}:$VERSION
        - docker push ${DOCKER_RPO_HUB_DEV}:latest

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=264a4d7b0f593f76848605e55d6d982c54c499cdc089cc5068f832a14b6abd62
  email:
    recipients:
      - ling_dark_portal@163.com
    on_success: never # default: change
    on_failure: always # default: always